#!/usr/bin/env python3
"""Create and verify baseline-specific scoring and neuron-selection provenance."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from neuron_responsibility.common import clean_output
from neuron_responsibility.evaluate import file_signature


def sha256(path: str | Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def score_contract(args: argparse.Namespace) -> dict:
    lagovad_config = ""
    if args.baseline == "lagovad" and args.baseline_weight:
        lagovad_config = str(Path(args.baseline_weight).with_name("config.yaml"))
    return {
        "schema": "baseline_specific_shift_score_v1",
        "baseline": args.baseline,
        "dataset": args.dataset,
        "source_train_csv": file_signature(args.source_train_csv),
        "baseline_weight": file_signature(args.baseline_weight),
        "sensitivity_weight": file_signature(args.sensitivity_weight),
        "consistency_weight": file_signature(args.consistency_weight),
        "lagovad_config": file_signature(lagovad_config),
    }


def prepare_score(args: argparse.Namespace) -> None:
    output = clean_output(args.out_dir, args.clean)
    path = output / "score_provenance.json"
    expected = score_contract(args)
    if path.exists():
        actual = json.loads(path.read_text(encoding="utf-8"))
        if actual != expected:
            raise RuntimeError(
                f"{path} belongs to another baseline/data/weight contract; use a clean output directory"
            )
        print(f"verified score provenance: {path}", flush=True)
        return
    occupied = [item for item in output.iterdir() if item.name != path.name]
    if occupied:
        raise RuntimeError(f"cannot certify pre-existing untracked score artifacts in {output}")
    path.write_text(json.dumps(expected, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"wrote score provenance: {path}", flush=True)


def seal_selection(args: argparse.Namespace) -> None:
    score_path = Path(args.score_provenance)
    neuron_path = Path(args.neuron_json)
    score = json.loads(score_path.read_text(encoding="utf-8"))
    if score.get("baseline") != args.baseline or score.get("dataset") != args.dataset:
        raise RuntimeError("score provenance does not match requested baseline/dataset")
    selection = json.loads(neuron_path.read_text(encoding="utf-8"))
    if selection.get("method") != "intravideo_paired_shift_global768":
        raise RuntimeError("unexpected neuron-selection method")
    if selection.get("dataset") != args.dataset:
        raise RuntimeError("selection dataset differs from requested dataset")
    payload = {
        "schema": "baseline_specific_shift_selection_v1",
        "baseline": args.baseline,
        "dataset": args.dataset,
        "score_provenance": score,
        "score_provenance_sha256": sha256(score_path),
        "selected_neurons_sha256": sha256(neuron_path),
    }
    output = Path(args.out_path)
    if output.exists():
        actual = json.loads(output.read_text(encoding="utf-8"))
        if actual != payload:
            raise RuntimeError(f"selection provenance mismatch: {output}")
        print(f"verified selection provenance: {output}", flush=True)
        return
    output.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"wrote selection provenance: {output}", flush=True)


def load_and_verify_selection_provenance(
    path: str,
    baseline: str,
    dataset: str,
    neuron_json: str,
) -> dict:
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    if payload.get("schema") != "baseline_specific_shift_selection_v1":
        raise RuntimeError("unsupported selection provenance schema")
    if payload.get("baseline") != baseline or payload.get("dataset") != dataset:
        raise RuntimeError("selection was generated by another baseline or dataset")
    if payload.get("selected_neurons_sha256") != sha256(neuron_json):
        raise RuntimeError("selected_neurons.json differs from its sealed provenance")
    return payload


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    prepare = subparsers.add_parser("prepare-score")
    prepare.add_argument("--baseline", choices=["dsanet", "desc", "lagovad"], required=True)
    prepare.add_argument("--dataset", choices=["ucf", "xd"], required=True)
    prepare.add_argument("--source-train-csv", required=True)
    prepare.add_argument("--baseline-weight", default="")
    prepare.add_argument("--sensitivity-weight", default="")
    prepare.add_argument("--consistency-weight", default="")
    prepare.add_argument("--out-dir", required=True)
    prepare.add_argument("--clean", action="store_true")
    seal = subparsers.add_parser("seal-selection")
    seal.add_argument("--baseline", choices=["dsanet", "desc", "lagovad"], required=True)
    seal.add_argument("--dataset", choices=["ucf", "xd"], required=True)
    seal.add_argument("--score-provenance", required=True)
    seal.add_argument("--neuron-json", required=True)
    seal.add_argument("--out-path", required=True)
    args = parser.parse_args()
    prepare_score(args) if args.command == "prepare-score" else seal_selection(args)


if __name__ == "__main__":
    main()
